### ISSUE TITLE
How to start using API?

### ISSUE THREAD

**Issue by scheung38** [tradestation/webapi-docs#20]
Not sure where to begin? Are there any examples?

**Comment by johnjelinek** [comment]
You'll need an API Key and Secret to get started. You can sign up from
https://developer.tradestation.com. There is sample code available at
https://github.com/tradestation.

**Comment by scheung38** [comment]
Thanks John are there costs in using and getting data from Tradestation and start trading real funds with it?

**Comment by johnjelinek** [comment]
All that info should also be up on https://developer.tradestation.com. If you don't
find what you're looking for, please email webapi@tradestation.com.

**Comment by nsbm60** [comment]
Why do I need to upload an image of my "government issued id" to join the developer program?  I'm already a customer!

**Comment by drancis** [comment]
Developer program is via TradeStation Technologies which is separate from TradeStation Securities.  This is why registration is separate and requires ID or passport.

**Comment by nsbm60** [comment]
Obviously not completely separate, given that it uses the TradeStation Securities login AND all my data, including my passport number from my TradeStation Securities account!

This process seems like it needs some work.  I signed up, but no confirmation email or any indication as to what happens next.  Will I get some kind of notification when my Developer account is active?

**Comment by whitethunder** [comment]
I completed the developer API form and was sad to find out that the platform is closed to new registrations. @johnjelinek any word on when that will open back up? Thanks!

**Comment by nsbm60** [comment]
It would appear, given the lack of any progress, that they've abandoned the API project.  There used to be a link from their home web page; last time I looked that was gone.  It's a shame, because unlike Interactive Brokers, TradeStation has a decent market data feed.

**Comment by drancis** [comment]
The TradeStation WebAPI offering is not abandon but has been a discretionary program since inception.  The current API was originally developed only as a means to feed our internal WebTrading and mobile applications.  Since it was not originally developed as a TDE with full libraries it requires support that is not currently allocated.  We are working to change that and officially productize the  offering so that it can be more readily available.  At this time we are working on alternate cloud based integration model and working to broaden availability.  If you would like to be considered for the WebAPI program you should start by completing our online questionnaire at (http://developer.tradestation.com/webapiform/).  As the program becomes available developers will be notified.

Thank you for your interest in the TradeStation WebAPI.

**Comment by whitethunder** [comment]
Thanks for the update @drancis. I'd love to write a Ruby wrapper for it. I filled out the form and hope to hear from you all soon.

**Comment by Catchops** [comment]
Does anyone know if there are any updates to this?  I just put in my application, but got the message that it was still closed.  I would love to know when it is going to be opened up again.

**Comment by goodiet** [comment]
@whitethunder @Catchops Just want to update you that I just submitted the questionnaire and got the same thing. Hope it will reopen soon. In the mean time, I'm using Interactive Broker.

**Comment by lancehunt** [comment]
@goodiet we are actively working on this again and have big plans for 2018...stay tuned.

**Comment by goodiet** [comment]
@lancehunt That is great to hear! Thank you for the update.

**Comment by shepware** [comment]
@drancis - thanks for the glimmer of hope.  I'm trying to find literally anywhere with simple access to options pricing data.  Yahoo and Google are depricated, and iex doesn't offer it.  TradeStation has pretty friendly documentation, and I was pretty bummed when the -sim didn't skirt the 401 error... next thing you know I'm reading about authentication... then how to sign up... then sortof miffed on what to sign up for.  Am I over thinking this - with all the documentation and pricing pages online, are there really no means for a user to pull snapshots of current and historical options price data for a single ticker?

**Comment by nsbm60** [comment]
@shepware I assume you are willing to pay for access to data?  The cheapest I've found is ActiveTick.  For $56/month you'll get realtime and historical data (that includes options) for 500 tickers.

**Comment by shepware** [comment]
@nsbm60 thanks for the tip, I'll check that out.  I'm hopeful that instead of paying a monthly fee I could find someone - maybe tradestation - that offers brokerage services and would freely offer visibility of asset prices through an API in exchange for taking my business, with some account minimum, away from Schwab... anything come to mind?

**Comment by FREENQ** [comment]
I just applied for the WebAPI but read this thread with a bit of disapointment. Mind the tech-friendly marketing approach of TradeStation I hope there´s good news soon. The competition from IB and NinjaTrader for the non-manual traders is starting to get hard to catch up on.

**Comment by lancehunt** [comment]
This repo is being archived as we have moved to https://github.com/tradestation/api-docs

There are no new updates on opening-up the TradeStation API at this time. When we decide on opening up this program further we will make an announcement on developer.tradestation.com
